### ISSUE TITLE
老哥 安卓11闪退

### ISSUE THREAD

**Issue by MiChongs** [jokerElsa/antiDouYinBurn#2]

**Comment by jokerElsa** [comment]
啥机型呢，去把权限显示再应用上层权限打开试试。

**Comment by MiChongs** [comment]
> 啥机型呢，去把权限显示再应用上层权限打开试试。

redmi note 10 pro，就首次启动申请了权限 后面就一直闪退

**Comment by jokerElsa** [comment]
手头试了个红米 note9pro 没问题
但是会出现每次都询问 是否允许启动抖音，感觉是你系统设置里面是不是阻拦了应用间跳转

**Comment by jokerElsa** [comment]
我又试了下 多点几次 就正常了 也不询问是否允许了。

**Comment by MiChongs** [comment]
> 手头试了个红米 note9pro 没问题 但是会出现每次都询问 是否允许启动抖音，感觉是你系统设置里面是不是阻拦了应用间跳转

可以了

**Comment by MiChongs** [comment]
> 我又试了下 多点几次 就正常了 也不询问是否允许了。

老哥 互star么😂😂

**Comment by jokerElsa** [comment]
点了😂

**Comment by MiChongs** [comment]
> 点了😂

你好像点错了 是那个Flipped😂😂😂

**Comment by jokerElsa** [comment]
不了不了，下次吧
